dist: xenial
sudo: false
language: php

cache:
    directories:
        - cache
        - projects
        - vendor
        - $HOME/.composer/cache

php:
  - 7.2

services:
  - mysql

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - mysql -e 'CREATE DATABASE doctrine_website_test;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('VdtLtifRh4gt37T') where User='root'; update user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pVdtLtifRh4gt37T
  - sudo service mysql restart

install:
  - rm composer.lock
  - travis_retry composer update -n --prefer-dist
  - travis_retry yarn install

jobs:
  include:
    - stage: Test
      env: DEPENDENCIES=low
      install:
        - rm composer.lock
        - travis_retry composer update --prefer-dist --prefer-lowest
        - travis_retry yarn install
      script:
        - ./vendor/bin/phpunit

    - stage: Test
      env: COVERAGE
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - ./phpunit --build-all --coverage-clover clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml

    - stage: Code Quality
      env: CODING_STANDARDS
      install: travis_retry composer install --prefer-dist
      script: ./vendor/bin/phpcs

    - stage: Code Quality
      env: STATIC_ANALYSIS
      install: travis_retry composer install --prefer-dist
      script: ./vendor/bin/phpstan analyse
