language: php

php:
    - 7.1

before_script: composer install

script:
    - ./vendor/bin/phpunit --debug
    - cp app/config/local.yml.dist app/config/local.yml
    - ./vendor/bin/sculpin build-docs --sync-git
    - ./vendor/bin/sculpin build-website
