parameters:
    doctrine.projects:
        orm:
            active: true
            name: Object Relational Mapper
            shortName: ORM
            slug: orm
            docsSlug: doctrine-orm
            composerPackageName: doctrine/orm
            repositoryName: doctrine2
            docsRepositoryName: doctrine2
            docsPath: /docs
            description: >
                PHP object relational mapper (ORM) that sits on top of a powerful
                database abstraction layer (DBAL). One of its key features is the
                option to write database queries in a proprietary object oriented
                SQL dialect called Doctrine Query Language (DQL). This provides developers
                with a powerful alternative to SQL that maintains flexibility without
                requiring unnecessary code duplication.

            keywords: [php, orm, mysql, object, data, mapper, mapping, query, dql]
            versions:
                -
                    name: '3.0'
                    branchName: 'master'
                    slug: 'latest'
                    upcoming: true
                -
                    name: '2.7'
                    branchName: '2.7'
                    slug: '2.7'
                    upcoming: true
                -
                    name: '2.6'
                    branchName: '2.6'
                    slug: '2.6'
                    current: true
                    aliases: ['current', 'stable']
                -
                    name: '2.5'
                    branchName: '2.5'
                    slug: '2.5'
                    maintained: false
                -
                    name: '2.4'
                    branchName: '2.4'
                    slug: '2.4'
                    maintained: false

        dbal:
            active: true
            name: Database Abstraction Layer
            shortName: DBAL
            slug: dbal
            docsSlug: doctrine-dbal
            composerPackageName: doctrine/dbal
            repositoryName: dbal
            docsRepositoryName: dbal
            docsPath: /docs
            description: >
                Powerful PHP database abstraction layer (DBAL) with many features
                for database schema introspection, schema management and PDO
                abstraction.
            keywords: [php, mysql, pgsql, dbal, database, abstraction]
            versions:
                -
                    name: '3.0'
                    branchName: 'develop'
                    slug: 'latest'
                    upcoming: true
                -
                    name: '2.8'
                    branchName: 'master'
                    slug: '2.8'
                    upcoming: true
                -
                    name: '2.7'
                    branchName: '2.7'
                    slug: '2.7'
                    current: true
                    aliases: ['current', 'stable']
                -
                    name: '2.6'
                    branchName: '2.6'
                    slug: '2.6'
                    maintained: false
                -
                    name: '2.5'
                    branchName: '2.5'
                    slug: '2.5'
                    maintained: false

        mongodb-odm:
            active: true
            name: MongoDB Object Document Mapper
            shortName: MongoDB ODM
            slug: mongodb-odm
            docsSlug: doctrine-mongodb-odm
            composerPackageName: doctrine/mongodb-odm
            repositoryName: mongodb-odm
            docsRepositoryName: mongodb-odm
            docsPath: /docs
            description: >
                PHP Doctrine MongoDB Object Document Mapper (ODM) provides transparent
                persistence for PHP objects to MongoDB.
            keywords: [php, mongodb, odm, data, mapper, mapping, object]
            versions:
                -
                    name: '2.0'
                    branchName: 'master'
                    slug: 'latest'
                    upcoming: true
                -
                    name: '1.2'
                    branchName: '1.2.x'
                    slug: '1.2'
                    current: true
                    aliases: ['current', 'stable', '1.2.x']
                -
                    name: '1.1'
                    branchName: '1.1.x'
                    slug: '1.1'
                    maintained: false
                    aliases: ['1.1.x']
                -
                    name: '1.0'
                    branchName: '1.0.x'
                    slug: '1.0'
                    maintained: false
                    aliases: ['1.0.x']

        phpcr-odm:
            active: true
            name: PHPCR ODM
            shortName: PHPCR ODM
            slug: phpcr-odm
            docsSlug: doctrine-phpcr-odm
            composerPackageName: doctrine/phpcr-odm
            repositoryName: phpcr-odm
            docsRepositoryName: phpcr-odm
            docsPath: /docs
            description: >
                PHP Doctrine Content Repository Object Document Mapper (ODM)
                provides transparent persistence for PHP objects.
            keywords: [php, content, odm, data, mapper, mapping, object]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']

        couchdb-odm:
            active: false
            name: CouchDB Object Document Mapper
            shortName: CouchDB ODM
            slug: couchdb-odm
            docsSlug: doctrine-couchdb-odm
            composerPackageName: doctrine/couchdb-odm
            repositoryName: couchdb-odm
            docsRepositoryName: couchdb-odm
            docsPath: /docs
            description: >
                PHP Doctrine CouchDB Object Document Mapper (ODM) provides
                transparent persistence for PHP objects to CouchDB.
            keywords: [couchdb, odm, data, mapper, mapping, object]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']

        migrations:
            active: true
            name: Migrations
            shortName: Migrations
            slug: migrations
            docsSlug: doctrine-migrations
            composerPackageName: doctrine/migrations
            repositoryName: migrations
            docsRepositoryName: migrations
            docsPath: /docs
            description: >
                PHP Doctrine Migrations project offer additional functionality
                on top of the database abstraction layer (DBAL) for versioning
                your database schema and easily deploying changes to it. It is
                a very easy to use and a powerful tool.
            keywords: [php, database, migrations, dbal]
            versions:
                -
                    name: '2.0'
                    branchName: 'master'
                    slug: 'latest'
                    upcoming: true
                -
                    name: '1.7'
                    branchName: '1.7'
                    slug: '1.7'
                    aliases: ['current', 'stable']
                    maintained: true
                    current: true

        common:
            active: true
            name: Common
            shortName: Common
            slug: common
            docsSlug: doctrine-common
            composerPackageName: doctrine/common
            repositoryName: common
            docsRepositoryName: common
            docsPath: /docs
            description: >
                PHP Doctrine Common project is a library that provides additional
                functionality that other Doctrine projects depend on such as better
                reflection support, persistence interfaces, proxies, event system
                and much more.
            keywords: [php, common, doctrine]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']

        mongodb:
            active: true
            name: MongoDB Abstraction Layer
            shortName: MongoDB
            slug: mongodb
            docsSlug: doctrine-mongodb
            composerPackageName: doctrine/mongodb
            repositoryName: mongodb
            hasDocs: true
            docsRepositoryName: mongodb
            docsPath: /docs
            description: >
                PHP Doctrine MongoDB project is a library that provides a wrapper
                around the native PHP Mongo PECL extension to provide additional
                functionality.
            keywords: [php, mongodb, abstraction]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']

        orientdb-odm:
            active: false
            name: OrientDB Object Document Mapper
            shortName: OrientDB ODM
            slug: orientdb-odm
            docsSlug: doctrine-orientdb-odm
            composerPackageName: doctrine/orientdb-odm
            repositoryName: orientdb-odm
            hasDocs: true
            docsRepositoryName: orientdb-odm
            docsPath: /docs
            codePath: /src
            description: >
                PHP OrientDB Object Document Mapper (ODM) provides transparent
                persistence for PHP objects to OrientDB.
            keywords: [php, orientdb, odm, data, mapper, mapping, object, graphdb]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']

        annotations:
            active: true
            name: Annotations
            shortName: Annotations
            slug: annotations
            docsSlug: doctrine-annotations
            composerPackageName: doctrine/annotations
            repositoryName: annotations
            docsRepositoryName: annotations
            docsPath: /docs
            description: >
                PHP Doctrine DocBlock Annotations Parser library that lets you parse
                structured data out of PHP docblocks for use with other functionality.
            keywords: [php, annotations, docblock, comment]
            versions:
                -
                    name: '2.0'
                    branchName: 'master'
                    slug: 'latest'
                    upcoming: true
                -
                    name: '1.7'
                    branchName: '1.7'
                    slug: '1.7'
                    upcoming: true
                -
                    name: '1.6'
                    branchName: '1.6'
                    slug: '1.6'
                    aliases: ['current', 'stable']
                    current: true
                    maintained: true

        collections:
            active: true
            name: Collections
            shortName: Collections
            slug: collections
            docsSlug: doctrine-collections
            composerPackageName: doctrine/collections
            repositoryName: collections
            hasDocs: true
            docsRepositoryName: collections
            docsPath: /docs
            description: >
                PHP Doctrine Collections library that adds additional functionality
                on top of PHP arrays.
            keywords: [php, collections, iterators]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']

        inflector:
            active: true
            name: Inflector
            shortName: Inflector
            slug: inflector
            docsSlug: doctrine-inflector
            composerPackageName: doctrine/inflector
            repositoryName: inflector
            hasDocs: true
            docsRepositoryName: inflector
            docsPath: /docs
            description: >
                PHP Doctrine Inflector is a small library that can perform
                string manipulations with regard to upper/lowercase and
                singular/plural forms of words.
            keywords: [php, strings, words, manipulation, inflector, inflection, uppercase, lowercase, singular, plural]
            versions:
                -
                    name: '1.3'
                    branchName: '1.3.x'
                    slug: '1.3'
                    current: true
                    aliases: ['current', 'stable']
                -
                    name: '2.0'
                    branchName: 'master'
                    slug: '2.0'
                    upcoming: true

        cache:
            active: true
            name: Cache
            shortName: Cache
            slug: cache
            docsSlug: doctrine-cache
            composerPackageName: doctrine/cache
            repositoryName: cache
            hasDocs: true
            docsRepositoryName: cache
            docsPath: /docs
            description: >
                PHP Doctrine Cache library is a popular cache implementation
                that supports many different drivers such as redis, memcache,
                apc, mongodb and others.
            keywords: [php, cache, abstraction, redis, memcache, couchdb, xcache, apc, riak]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']

        lexer:
            active: true
            name: Lexer
            shortName: Lexer
            slug: lexer
            docsSlug: doctrine-lexer
            composerPackageName: doctrine/lexer
            repositoryName: lexer
            hasDocs: true
            docsRepositoryName: lexer
            docsPath: /docs
            description: >
                PHP Doctrine Lexer parser library that can be used in Top-Down,
                Recursive Descent Parsers.
            keywords: [php, parser, lexer, annotations, docblock]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']

        event-manager:
            active: true
            name: Event Manager
            shortName: Event Manager
            slug: event-manager
            docsSlug: doctrine-event-manager
            composerPackageName: doctrine/event-manager
            repositoryName: event-manager
            docsRepositoryName: event-manager
            docsPath: /docs
            description: >
                The Doctrine Event Manager is a simple PHP event system that was built to be used with
                the various Doctrine projects.

            keywords: [events, event manager, event system]
            versions:
                -
                    name: '1.0'
                    branchName: 'master'
                    slug: 'latest'
                    current: true
                    aliases: ['current', 'stable']

        persistence:
            active: true
            name: Persistence
            shortName: Persistence
            slug: persistence
            docsSlug: doctrine-persistence
            composerPackageName: doctrine/persistence
            repositoryName: persistence
            docsRepositoryName: persistence
            docsPath: /docs
            description: >
                The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine
                object mappers share.
            keywords: [persistence, object, mapper, orm, odm]
            versions:
                -
                    name: '1.0'
                    branchName: 'master'
                    slug: 'latest'
                    current: true
                    aliases: ['current', 'stable']

        reflection:
            active: true
            name: Reflection
            shortName: Reflection
            slug: reflection
            docsSlug: doctrine-reflection
            composerPackageName: doctrine/reflection
            repositoryName: reflection
            docsRepositoryName: reflection
            docsPath: /docs
            description: >
                The Doctrine Reflection project is a simple library used by the various Doctrine projects which
                adds some additional functionality on top of the reflection functionality that comes with PHP.
                It allows you to get the reflection information about classes, methods and properties statically.

            keywords: [reflection, static]
            versions:
                -
                    name: '1.0'
                    branchName: 'master'
                    slug: 'latest'
                    current: true
                    aliases: ['current', 'stable']

        coding-standard:
            active: true
            name: Coding Standard
            shortName: Coding Standard
            slug: coding-standard
            docsSlug: doctrine-coding-standard
            composerPackageName: doctrine/coding-standard
            repositoryName: coding-standard
            docsRepositoryName: coding-standard
            docsPath: /docs
            description: >
                The Doctrine Coding Standard is a set of PHPCS rules applied to all Doctrine projects.

            keywords: [coding, standard, rules, sniffs, checks]
            versions:
                -
                    name: '5.0'
                    branchName: 'master'
                    slug: 'latest'
                    upcoming: true
                -
                    name: '4.0'
                    branchName: '4.x'
                    slug: '4.0'
                    current: true
                    aliases: ['current', 'stable']

        doctrine1:
            active: false
            archived: true
            name: Doctrine1 ORM
            shortName: Doctrine1
            slug: doctrine1
            docsSlug: doctrine1
            repositoryName: doctrine1
            hasDocs: true
            docsRepositoryName: doctrine1-documentation
            docsPath: /source
            description: >
                PHP 5 Doctrine1 Object Relational Mapper (ORM)
            keywords: [php, doctrine1, orm]
            versions:
                -
                    name: 'master'
                    branchName: 'master'
                    slug: 'latest'
                    aliases: ['current', 'stable']
