sculpin_content_types:
    posts:
        type: path
        path: _posts
        permalink: :year/:month/:day/:filename/
        taxonomies:
            - tags
            - categories

sculpin_rst:
    demote_headings: false

timbroder_algolia:
    enabled: false
    options:
        application_id: YVYTFT9XMW
        admin_api_key: 8c7a98e9db76e2df59893bf11f632675
        index: pages
        clear_on_sync: true

sculpin_twig:
    source_view_paths: ['_views', '_layouts', '_partials', '_includes']
    extensions: ['', 'twig', 'html', 'html.twig', 'twig.html', 'rst']

services:
    doctrine.twig.main.extension:
        class: Doctrine\Website\Twig\MainExtension
        public: false
        arguments:
            - '%doctrine.team_members%'
        tags:
            - { name: twig.extension }

    doctrine.twig.project.extension:
        class: Doctrine\Website\Twig\ProjectExtension
        public: false
        arguments:
            - '@doctrine.project.repository'
        tags:
            - { name: twig.extension }

    doctrine.twig.docs.extension:
        class: Doctrine\Website\Twig\DocsExtension
        public: false
        arguments:
            - '@doctrine.project.repository'
        tags:
            - { name: twig.extension }

    doctrine.project.factory:
        class: Doctrine\Website\Projects\ProjectFactory
        public: false

    doctrine.project.repository:
        class: Doctrine\Website\Projects\ProjectRepository
        public: true
        arguments:
            - '%doctrine.projects%'
            - '@doctrine.project.factory'

parameters:
    doctrine.team_members:
        ocramius:
            slug: ocramius
            name: Marco Pivetta
            twitter: ocramius
            github: ocramius
            website: https://ocramius.github.io/
            email: ocramius@gmail.com
        jwage:
            slug: jwage
            name: Jonathan H. Wage
            twitter: jwage
            github: jwage
            website: https://jwage.com
            email: jonwage@gmail.com
        guilhermeblanco:
            slug: guilhermeblanco
            name: Guilherme Blanco
            twitter: guilhermeblanco
            github: guilhermeblanco
            email: guilhermeblanco@gmail.com

    doctrine.projects:
        orm:
            name: Object Relational Mapper
            shortName: ORM
            slug: orm
            docsSlug: doctrine-orm
            composerPackageName: doctrine/orm
            repositoryName: doctrine2
            docsRepositoryName: doctrine2
            docsPath: /docs
            description: Object relational mapper (ORM) for PHP that sits on top of a powerful database abstraction layer (DBAL). One of its key features is the option to write database queries in a proprietary object oriented SQL dialect called Doctrine Query Language (DQL), inspired by Hibernates HQL. This provides developers with a powerful alternative to SQL that maintains flexibility without requiring unnecessary code duplication.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest
                -
                    name: 2.6
                    branchName: 2.6
                    slug: 2.6
                    current: true
                -
                    name: 2.5
                    branchName: 2.5
                    slug: 2.5

        dbal:
            name: Database Abstraction Layer
            shortName: DBAL
            slug: dbal
            docsSlug: doctrine-dbal
            composerPackageName: doctrine/dbal
            repositoryName: dbal
            docsRepositoryName: dbal
            docsPath: /docs
            description: Powerful database abstraction layer with many features for database schema introspection, schema management and PDO abstraction.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest
                -
                    name: 2.6
                    branchName: 2.6
                    slug: 2.6
                    current: true
                -
                    name: 2.5
                    branchName: 2.5
                    slug: 2.5

        mongodb-odm:
            name: MongoDB Object Document Mapper
            shortName: MongoDB ODM
            slug: mongodb-odm
            docsSlug: doctrine-mongodb-odm
            composerPackageName: doctrine/mongodb-odm
            repositoryName: mongodb-odm
            docsRepositoryName: mongodb-odm
            docsPath: /docs
            description: Doctrine MongoDB Object Document Mapper provides transparent persistence for PHP objects.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest
                -
                    name: 1.2
                    branchName: 1.2.x
                    slug: 1.2
                    current: true
                -
                    name: 1.1
                    branchName: 1.1.x
                    slug: 1.1

        phpcr-odm:
            name: PHPCR ODM
            shortName: PHPCR ODM
            slug: phpcr-odm
            docsSlug: doctrine-phpcr-odm
            composerPackageName: doctrine/phpcr-odm
            repositoryName: phpcr-odm
            docsRepositoryName: phpcr-odm-documentation
            docsPath: /
            description: Doctrine PHPCR Object Document Mapper provides transparent persistence for PHP objects.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        couchdb-odm:
            name: CouchDB Object Document Mapper
            shortName: CouchDB ODM
            slug: couchdb-odm
            docsSlug: doctrine-couchdb-odm
            composerPackageName: doctrine/couchdb-odm
            repositoryName: couchdb-odm
            docsRepositoryName: couchdb-documentation
            docsPath: /
            description: Doctrine CouchDB Object Document Mapper provides transparent persistence for PHP objects.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        migrations:
            name: Migrations
            shortName: Migrations
            slug: migrations
            docsSlug: doctrine-migrations
            composerPackageName: doctrine/migrations
            repositoryName: migrations
            docsRepositoryName: migrations-documentation
            docsPath: /
            description: The Doctrine Migrations offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it. It is a very easy to use and powerful tool.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        common:
            name: Common
            shortName: Common
            slug: common
            docsSlug: doctrine-common
            composerPackageName: doctrine/common
            repositoryName: common
            docsRepositoryName: common-documentation
            docsPath: /
            description: The Doctrine Common project is a library that provides extensions to core PHP functionality.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        mongodb:
            name: MongoDB Abstraction Layer
            shortName: MongoDB
            slug: mongodb
            docsSlug: doctrine-mongodb
            composerPackageName: doctrine/mongodb
            repositoryName: mongodb
            hasDocs: true
            docsRepositoryName: mongodb
            docsPath: /docs
            description: The Doctrine MongoDB project is a library that provides a wrapper around the native PHP Mongo PECL extension to provide additional functionality.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        orientdb-odm:
            name: OrientDB Object Document Mapper
            shortName: OrientDB ODM
            slug: orientdb-odm
            docsSlug: doctrine-orientdb-odm
            composerPackageName: doctrine/orientdb-odm
            repositoryName: orientdb-odm
            hasDocs: true
            docsRepositoryName: orientdb-odm
            docsPath: /docs
            codePath: /src
            description: Doctrine OrientDB Object Document Mapper provides transparent persistence for PHP objects.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        annotations:
            name: Annotations
            shortName: Annotations
            slug: annotations
            docsSlug: doctrine-annotations
            composerPackageName: doctrine/annotations
            repositoryName: annotations
            hasDocs: false
            docsRepositoryName: annotations
            docsPath: /docs
            description: Docblock Annotations Parser library.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        collections:
            name: Collections
            shortName: Collections
            slug: collections
            docsSlug: doctrine-collections
            composerPackageName: doctrine/collections
            repositoryName: collections
            hasDocs: true
            docsRepositoryName: collections
            docsPath: /docs
            description: Collections abstraction library.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        inflector:
            name: Inflector
            shortName: Inflector
            slug: inflector
            docsSlug: doctrine-inflector
            composerPackageName: doctrine/inflector
            repositoryName: inflector
            hasDocs: true
            docsRepositoryName: inflector
            docsPath: /docs
            description: Doctrine Inflector is a small library that can perform string manipulations with regard to upper-/lowercase and singular/plural forms of words.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        cache:
            name: Cache
            shortName: Cache
            slug: cache
            docsSlug: doctrine-cache
            composerPackageName: doctrine/cache
            repositoryName: cache
            hasDocs: true
            docsRepositoryName: cache
            docsPath: /docs
            description: Cache component extracted from the Doctrine Common project.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest

        lexer:
            name: Lexer
            shortName: Lexer
            slug: lexer
            docsSlug: doctrine-lexer
            composerPackageName: doctrine/lexer
            repositoryName: lexer
            hasDocs: true
            docsRepositoryName: lexer
            docsPath: /docs
            description: Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
            versions:
                -
                    name: master
                    branchName: master
                    slug: latest
