imports:
    - config.yml

parameters:
    doctrine.website.url: 'https://www.doctrine-project.org'
    doctrine.website.google_analytics_tracking_id: 'UA-288343-7'
    doctrine.website.stripe.publishable_key: 'pk_live_54QFCgqHDYHZ1tFxg95JhYRR00kICoxvNS'
