services:
    sculpin_rst.twig.loader:
        public: false
        class: Sculpin\Bundle\TwigBundle\FilesystemLoader
        tags: [{ name: twig.loaders.append }]

    sculpin_rst.converter.rst:
        class: Doctrine\Website\SculpinRstBundle\Converter\RstConverter
        arguments:
            - @sculpin_rst.parser_factory
            - %sculpin_rst.extensions%
        tags:
            - { name: sculpin.converter, alias: rst }
            - { name: sculpin.custom_mime_extensions, type: text/x-rst, parameter: sculpin_rst.extensions }
            - { name: kernel.event_subscriber }

    sculpin_rst.parser_factory:
        public: false
        class: Doctrine\Website\SculpinRstBundle\Parser\ParserFactory
        arguments:
            - @sculpin_rst.kernel.sculpin

    sculpin_rst.kernel.sculpin:
        public: true
        class: Doctrine\Website\SculpinRstBundle\Kernel\Kernel
        arguments:
            - @sculpin_rst.kernel.html
            - []
            - []

    sculpin_rst.kernel.html:
        public: false
        class: Gregwar\RST\HTML\Kernel

    sculpin_rst.directive.contents:
        public: false
        class: Doctrine\Website\SculpinRstBundle\Directive\ContentsDirective
        arguments: [ @sculpin_twig.twig, %sculpin_rst.directive_domain% ]
        tags: [{ name: sculpin.rst.directive }]

    sculpin_rst.directive.figure:
        public: false
        class: Doctrine\Website\SculpinRstBundle\Directive\FigureDirective
        arguments: [ @sculpin_twig.twig, %sculpin_rst.directive_domain% ]
        tags: [{ name: sculpin.rst.directive }]

    sculpin_rst.directive.pull_quote:
        public: false
        class: Doctrine\Website\SculpinRstBundle\Directive\PullQuoteDirective
        arguments: [ %sculpin_rst.directive_domain% ]
        tags: [{ name: sculpin.rst.directive }]

    sculpin_rst.listener.demote_headings:
        class: Doctrine\Website\SculpinRstBundle\Listener\DemoteHeadingsListener
